---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared
  namespace: platform
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBHQQsL8rH+7hf7pUv6y91wcAfJ0rk0Fb0MPC2ztTfMBDxJpzoJ2IrX+Uu7jxiT9h8hn2aFXR3FdZsvIYv6oO6vfq+0AJXwrseICH7W1hBpwrGy1uB5nUHWBYFHhCpFhAfrug0026RKF0a/vZ4fIfgCkT32SOuoiVGc36PtGiWa8YYTrxPstD7wN+7SCPsgrgVIo9JZhfftgVu9+QfdXLxEsoaatI9X1hFM0fcJpuZeuh4MmSCVeClBkFI0o7cOQ6/3jNSduJZr0FyDP6CqAnbM1mxsgnUT6SrWBX8ZWoWxE6A5oV+R/GPrKml8+h7bBtCg1IsZ8YpWeigmQ1R5PzCrxBRkgMEt9A8GmgDl1QCRBTF4ULg05CxxPU2xsoFbgcYcJL1UE9ZLkaqcX2rZfdwPYebOIfozEbjDKn5IB0POoqI0JsG2QQLeevVxcxqRNQHgZYH1axcBoW0aKiS3yGtna3AoWT1bsn+m38sjNomj6ACuMtGR2C60cUUTO2soVwMpgkSZ82RVFOJET2JdN3+IvFv1rwy5FovAMnOtJkC6dcElWOJsOMgn/CgdBvt60LAMKdqhhvPw3+C1smBHjKLpgC3giu8kn5UmmB8j7i2nPjEexTl5HuDQ2+KNmioALuQWbFf6GdgBSxM+25bpRfGDGi92osHGld9HxRLEinCBmh0+1m9seQv59NpKxmJlC8kD3bFqhOZ3jhLNst98i80reGqmIdy9AcL6QXAfFdizlK52OIEI1uQgJVXtbNGo+7wEd6f56j5ETg3NFqoK3/mPRsORejE6khnTrRr1NHAp7dpITPzV9hGkNvsMNrzoyFRAPbNwqCLx7C+xRXzHAJipruvdPhhd7TZnH3lbUEO1oFmnjgaHkB8BlGR5CZwDrElPIk5JUrXr3+YWnP0sUbZs5VGvtcW+sWeSW58frM7Tdy/M/T5pJo8s
  template:
    metadata:
      name: cloudflared
      namespace: platform
