apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - namespace.yaml
  - secret.yaml
  - vmcp-db.yaml
  - home.yaml
  - quiz.yaml
  - vmcp.yaml
  - ingress.yaml
